### PR TITLE
Add leungmichael.com

### PR DESCRIPTION
**Pull request by MiLeung**
Project details:

* Club: Austin High School
* Name: leungmichael.com
* Description: Leungmichael.com is just a personal website I made from the skills I learned at HackEDU's Hack Camp. On this website, I will be posting current and already finished coding projects.
* URL: http://leungmichael.com/
* GitHub: https://github.com/MiLeung/MiLeung.github.io
* Authors:
  * Michael Leung

:shipit:

### CODE REVIEW

**Comment by zachlatta** [comment]
Awesome! I'll cherry pick this over to master when I get to a computer.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MiLeung** [comment]
By the way, my club should be HackEDU Hack Camp!

**Comment by zachlatta** [comment]
Cherry picked to master with small modifications in 38d2f6327c76ce7b6e74ff2e0de828727fbfa3cd.

Thanks Michael!

**Comment by zachlatta** [comment]
Would love to talk about the possibility! I'll shoot you an email.

On Wed, Aug 19, 2015 at 6:40 PM, Michael Leung <notifications@github.com>
wrote:

> By the way, my club should be HackEDU Hack Camp!
>
> On Wed, Aug 19, 2015 at 6:08 PM, Zach Latta <notifications@github.com>
> wrote:
>
> > Awesome! I'll cherry pick this over to master when I get to a computer.
> >
> > --
> > Zach Latta
> > http://zachlatta.com
> > https://github.com/zachlatta
> > https://twitter.com/zachlatta
> >
> > On Aug 18, 2015, 11:53 PM -0700, Michael Leung<notifications@github.com
> >,
> > wrote:
> > >
> > > Project details:
> > >
> > > Club: Austin High School
> > > Name: leungmichael.com
> > > Description: Leungmichael.com is just a personal website I made from
> the
> > skills I learned at HackEDU's Hack Camp. On this website, I will be
> posting
> > current and already finished coding projects.
> > > URL:http://leungmichael.com/
> > > GitHub:https://github.com/MiLeung/MiLeung.github.io
> > > Authors:
> > > Michael Leung
> > >
> > >
> > >
> > >
> > >
> > >
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/hackedu/shipped/pull/76
> > >
> > > Commit Summary
> > > projects: add leungmichael.com
> > >
> > > File Changes
> > > A_data/projects/austin_high_school/leungmichael.com.yml(
> > https://github.com/hackedu/shipped/pull/76/files#diff-0)(6)
> > >
> > > Patch Links:
> > > https://github.com/hackedu/shipped/pull/76.patch
> > > https://github.com/hackedu/shipped/pull/76.diff
> > >
> > >
> > > —
> > > Reply to this email directly orview it on GitHub(
> > https://github.com/hackedu/shipped/pull/76).
> > >
> > >
> > >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hackedu/shipped/pull/76#issuecomment-132841932>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/shipped/pull/76#issuecomment-132846522>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Pull request closed without merging**
