### PR TITLE
add 'Add Project' link

### PR DESCRIPTION
**Pull request by ad510**
This generally works, but the button gets covered by the "Fork me on GitHub" button if the window is too narrow. Any suggestions to fix that?

### CODE REVIEW

**Comment by ad510** [comment]
I think this should be ready to merge in now, but feel free to make more changes if you think that's appropriate.

**Comment by zachlatta** [comment]
@MaxWofford can you merge this into a branch called `add-project-link` and make the necessary changes to make the whole area clickable and get it ready to be merged?

**Comment by ad510** [comment]
What do you mean by "make the whole area clickable"? I might be able to make that change myself.

**Comment by zachlatta** [comment]
Not entirely sure, I was referring to Max's comment "Is there a way to
make only non-alpha areas of the button clickable?".

--
Zach Latta http://zachlatta.com https://github.com/zachlatta
https://twitter.com/zachlatta


On Mon, Jan 12, 2015, at 09:23 PM, Andrew Downing wrote:
> What do you mean by "make the whole area clickable"? I might be able
> to make that change myself.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/hackedu/shipped/pull/43#issuecomment-69697206

**Comment by MaxWofford** [comment]
@zachlatta I don't think we want the whole area clickable. That is the current setup, which can be confusing. I can click in the space next to the "fork me" button, and I will be sent to the repo.

**Comment by zachlatta** [comment]
Ah, gotcha gotcha. I was referring to making that fix.

--
Zach Latta http://zachlatta.com https://github.com/zachlatta
https://twitter.com/zachlatta


On Mon, Jan 12, 2015, at 11:52 PM, Max Wofford wrote:
> @zachlatta[1] I don't think we want the whole area clickable. That is
> the current setup, which can be confusing. I can click in the space
> next to the "fork me" button, and I will be sent to the repo.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/zachlatta
  2. https://github.com/hackedu/shipped/pull/43#issuecomment-69707521

**Comment by ad510** [comment]
@MaxWofford I made a new commit to use an image map so that only a triangular part of the "fork me" button is clickable.

**Pull request merged**
