### PR TITLE
Add Furfante

### PR DESCRIPTION
**Pull request by gemmabusoni**
Project details:

* Club: Austin High School
* Name: Furfante
* Description: You fly around in a virtual city and destroy stuff. It's like a super hero game, but not.
* GitHub: https://github.com/gemmabusoni/HackSC
* Authors:
  * Gemma Busoni

:shipit:

### CODE REVIEW

**Comment by jonleung** [comment]
@gemmabusoni is there any way that we could link to a live demo for this?

**Comment by zachlatta** [comment]
Sorry about the failing build. I believe there was a breaking change in the upstream `jekyll/jekyll` Docker image that was fixed in #74.

**Comment by zachlatta** [comment]
If you rebase master onto your branch the issue should be removed.

**Comment by zachlatta** [comment]
Thanks @gemmabusoni!

I went ahead and cherry picked it into master in 38f3123d7a7b6f7f930f85e3fefbf251ed0ecc63.

**Pull request closed without merging**
