### PR TITLE
remove just click the link

### PR DESCRIPTION
**Pull request by gemmabusoni**
Really inappropriate; pointed out by Mr. Schorr from South Pas.

### CODE REVIEW

**Comment by paked** [comment]
:+1:

**Comment by paked** [comment]
@zachlatta this is the kind of thing that should have *some* sort of coverage in a code of conduct. IMO

**Comment by zachlatta** [comment]
Thank you @gemmabusoni.

And I agree @paked. I'd love to hear any other thoughts you have in hackedu/meta#117.

I'm going to diagnose why the test isn't passing when I get home and then merge it.

What are everyone's thoughts on forcing a `NSFW` tag on content like this in the future, instead of deleting it?

**Comment by paked** [comment]
@zachlatta I'll take a look now.

In an ideal world, I think the `NSFW` tag would work well. It certainly sits better morally than __banning submissions__. However, I would put yourself in the perspective of a school. At least in Australia, schools are not really supposed to allow students to view any potential NSFW content. I am pretty sure that this system would fall in the banned category.

**Pull request closed without merging**
