### PR TITLE
add getting started section to readme. closes #52

### LINKED ISSUE #52: Add section to readme on getting started
Prereqs:

* Jekyll

How to run server

That sort of thing

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
This is a small stylistic thing, but since the code snippet is so short, I would probably just use four spaces to indent instead of using the three backticks.

**Comment by zachlatta** [comment]
Hmm, can you also resolve the merge conflict by merging master into this branch?

**Comment by MaxWofford** [comment]
Got it! Is there a way to define syntax highlighting using the four spaces method of code highlighting?

**Comment by zachlatta** [comment]
Oh, good point. Not that I know of.

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Pull request merged**
