### PR TITLE
fix issue#51

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
Tested on chromium and firefox. This solution should work with everything but IE 8&9: http://caniuse.com/#feat=multicolumn

**Comment by MaxWofford** [comment]
@ad510 Can you test this on safari?

**Comment by ad510** [comment]
I worked on the website on an account at metagross.hackedu.us but I forgot how to log into it. Maybe ask @jonleung who also has OS X? Or temporarily host it somewhere and tell me what the URL is.

**Comment by MaxWofford** [comment]
Works on safari for @jonleung.

**Pull request merged**
